import type { Metadata } from "next";
import "./globals.css";
import { PartnerProvider } from "./partnerProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <PartnerProvider>
          {children}

        </PartnerProvider>
      </body>
    </html>
  );
}
