import type { Metadata } from "next";

import "./globals.css";
import { ClientProvider } from "./clientProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="flex flex-col h-screen">
        <ClientProvider>
          <main className="flex-grow">
            {children}
          </main>
          
        </ClientProvider>
      </body>
    </html>
  );
}
