import type { Metadata } from "next";
import "./globals.css";
import { AdminProviders } from "./adminProviders";
import { Toaster } from "sonner";



export const metadata: Metadata = {
  title: "Admin App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AdminProviders>
         {children}
         <Toaster richColors position="top-center" duration={1500}/>
        </AdminProviders>
      </body>
    </html>
  );
}
